name: Distribute

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  site-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    env:
      MNEMONIC: ${{ secrets.MNEMONIC }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Disperse Tokens
        run: yarn disperse

      - name: Push Changes
        uses: actions-x/commit@v6
