name: Distribute

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  distribute:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .

    env:
      MNEMONIC: ${{ secrets.MNEMONIC }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Disperse Tokens
        run: yarn disperse

      - name: Push Changes
        uses: actions-x/commit@v6
        with:
          name: "Github Actions Distributor"
          message: "Automatic distribution"
